version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go build
      - run: sudo apt-get update && sudo apt-get install rsync
      - run: rsync -v -e "ssh -o StrictHostKeyChecking=no" blink blink@142.93.26.159:/home/blink/blink/blink
      - run: ssh -o "StrictHostKeyChecking no" blink@142.93.26.159 "systemctl --user restart blink || systemctl --user start blink"
